databases:
  - name: srtask-db
    plan: free
    databaseName: srtask
    user: srtask

services:
  - type: web
    name: srtask
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn srtask.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: srtask-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.2"
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
      - key: DJANGO_SUPERUSER_USERNAME
        value: "stradmin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "strogers3@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "changeme123"
